import { ProjectTemplate } from "./types";

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    name: "Bathroom Remodel",
    project_type: "Bathroom Remodel",
    blocks: [
      {
        title: "Bathroom Demolition",
        description: "Remove existing fixtures, tile, vanity, and flooring.",
        trade_type: "Carpenter",
        special_requirements: "Cap all plumbing lines before demo.",
        depends_on: [],
      },
      {
        title: "Plumbing Rough-In",
        description: "Relocate or update supply and drain lines per new layout.",
        trade_type: "Plumber",
        special_requirements: "Permit required.",
        depends_on: [0],
      },
      {
        title: "Electrical Updates",
        description: "Update wiring for new lighting, fan, and GFCI outlets.",
        trade_type: "Electrician",
        special_requirements: "All outlets must be GFCI protected.",
        depends_on: [0],
      },
      {
        title: "Waterproofing & Tile",
        description: "Apply waterproofing membrane, install wall and floor tile.",
        trade_type: "Tile Installer",
        special_requirements: "Use Kerdi or equivalent waterproofing system.",
        depends_on: [1, 2],
      },
      {
        title: "Vanity & Fixture Installation",
        description: "Install vanity, toilet, faucets, shower fixtures, and accessories.",
        trade_type: "Plumber",
        special_requirements: "",
        depends_on: [3],
      },
      {
        title: "Painting & Trim",
        description: "Paint walls and ceiling. Install baseboards and trim.",
        trade_type: "Painter",
        special_requirements: "Use moisture-resistant paint.",
        depends_on: [3],
      },
    ],
  },
  {
    name: "Kitchen Remodel",
    project_type: "Kitchen Remodel",
    blocks: [
      {
        title: "Kitchen Demolition",
        description: "Remove existing cabinets, countertops, backsplash, and flooring.",
        trade_type: "Carpenter",
        special_requirements: "Protect adjacent rooms.",
        depends_on: [],
      },
      {
        title: "Electrical Rough-In",
        description: "Run new circuits for appliances and lighting.",
        trade_type: "Electrician",
        special_requirements: "Must comply with current NEC code.",
        depends_on: [0],
      },
      {
        title: "Plumbing Rough-In",
        description: "Update or relocate water supply and drain lines.",
        trade_type: "Plumber",
        special_requirements: "Include gas line if needed.",
        depends_on: [0],
      },
      {
        title: "Cabinet Installation",
        description: "Install wall and base cabinets per design plan.",
        trade_type: "Carpenter",
        special_requirements: "Level to within 1/16 inch.",
        depends_on: [1, 2],
      },
      {
        title: "Countertop Installation",
        description: "Template, fabricate, and install countertops.",
        trade_type: "Carpenter",
        special_requirements: "Template after cabinets are complete.",
        depends_on: [3],
      },
      {
        title: "Electrical Finish",
        description: "Install outlets, switches, and light fixtures.",
        trade_type: "Electrician",
        special_requirements: "",
        depends_on: [3],
      },
      {
        title: "Plumbing Fixtures",
        description: "Install sink, faucet, garbage disposal, dishwasher connection.",
        trade_type: "Plumber",
        special_requirements: "",
        depends_on: [4],
      },
      {
        title: "Tile Backsplash",
        description: "Install tile backsplash from countertop to underside of wall cabinets.",
        trade_type: "Tile Installer",
        special_requirements: "",
        depends_on: [4],
      },
      {
        title: "Painting",
        description: "Paint walls, ceiling, and touch up any trim.",
        trade_type: "Painter",
        special_requirements: "",
        depends_on: [5, 7],
      },
    ],
  },
  {
    name: "Deck Construction",
    project_type: "Deck Construction",
    blocks: [
      {
        title: "Site Preparation & Footings",
        description: "Excavate, set footings, and pour concrete piers.",
        trade_type: "Carpenter",
        special_requirements: "Permit and inspection required.",
        depends_on: [],
      },
      {
        title: "Framing",
        description: "Install ledger board, beams, joists, and blocking.",
        trade_type: "Carpenter",
        special_requirements: "Use pressure-treated lumber.",
        depends_on: [0],
      },
      {
        title: "Electrical for Outdoor Lighting",
        description: "Run circuits for deck lighting and outdoor outlets.",
        trade_type: "Electrician",
        special_requirements: "All outdoor-rated and GFCI protected.",
        depends_on: [1],
      },
      {
        title: "Decking & Railings",
        description: "Install deck boards, railings, and stairs.",
        trade_type: "Carpenter",
        special_requirements: "Railing must meet local code height requirements.",
        depends_on: [1],
      },
      {
        title: "Finishing & Staining",
        description: "Sand, stain, and seal all wood surfaces.",
        trade_type: "Painter",
        special_requirements: "Use exterior-grade stain/sealer.",
        depends_on: [2, 3],
      },
    ],
  },
  {
    name: "House Construction",
    project_type: "New Home Build",
    blocks: [
      {
        title: "Site Work & Foundation",
        description: "Clear lot, excavate, pour footings and foundation walls. Waterproof and backfill.",
        trade_type: "Concrete",
        special_requirements: "Soil test and survey required. Permit needed before excavation.",
        depends_on: [],
      },
      {
        title: "Rough Plumbing (Underground)",
        description: "Install underground drains, sewer line, and water service before slab or subfloor.",
        trade_type: "Plumber",
        special_requirements: "Must pass underground inspection before concrete.",
        depends_on: [0],
      },
      {
        title: "Framing",
        description: "Frame walls, floors, roof structure, and install sheathing, windows, and exterior doors.",
        trade_type: "Carpenter",
        special_requirements: "Follow engineered plans. Framing inspection required.",
        depends_on: [0],
      },
      {
        title: "Roofing",
        description: "Install underlayment, shingles or metal roofing, flashing, and gutters.",
        trade_type: "Roofer",
        special_requirements: "Ice and water shield at eaves and valleys.",
        depends_on: [2],
      },
      {
        title: "Electrical Rough-In",
        description: "Run all wiring, install panel, outlets, switch boxes, and low-voltage wiring.",
        trade_type: "Electrician",
        special_requirements: "NEC code compliance. Arc-fault and GFCI per current code.",
        depends_on: [2],
      },
      {
        title: "Plumbing Rough-In",
        description: "Run supply, drain, and vent lines for all fixtures. Install tub/shower units.",
        trade_type: "Plumber",
        special_requirements: "Pressure test all lines. Permit required.",
        depends_on: [2],
      },
      {
        title: "HVAC Rough-In",
        description: "Install ductwork, furnace/air handler, and refrigerant lines. Set condensing unit pad.",
        trade_type: "HVAC",
        special_requirements: "Manual J load calculation required.",
        depends_on: [2],
      },
      {
        title: "Insulation",
        description: "Install wall, floor, and attic insulation. Air seal all penetrations.",
        trade_type: "Carpenter",
        special_requirements: "Must meet energy code R-values. Inspection required before drywall.",
        depends_on: [4, 5, 6],
      },
      {
        title: "Drywall",
        description: "Hang, tape, mud, and sand all drywall. Texture ceilings if specified.",
        trade_type: "Carpenter",
        special_requirements: "Level 4 finish on painted surfaces, Level 5 under lighting.",
        depends_on: [7],
      },
      {
        title: "Interior Trim & Doors",
        description: "Install baseboards, casing, crown molding, interior doors, and closet shelving.",
        trade_type: "Carpenter",
        special_requirements: "Use paint-grade or stain-grade per plan.",
        depends_on: [8],
      },
      {
        title: "Painting (Interior)",
        description: "Prime and paint all walls, ceilings, and trim. Two coats on walls.",
        trade_type: "Painter",
        special_requirements: "Primer required on new drywall.",
        depends_on: [9],
      },
      {
        title: "Tile & Flooring",
        description: "Install tile in bathrooms and kitchen. Install hardwood, LVP, or carpet in remaining rooms.",
        trade_type: "Tile Installer",
        special_requirements: "Waterproof membrane in wet areas.",
        depends_on: [8],
      },
      {
        title: "Cabinet & Countertop Installation",
        description: "Install kitchen and bathroom cabinets and countertops.",
        trade_type: "Carpenter",
        special_requirements: "Template countertops after cabinets are set and leveled.",
        depends_on: [8],
      },
      {
        title: "Electrical Finish",
        description: "Install all fixtures, outlets, switches, and panels. Connect appliances.",
        trade_type: "Electrician",
        special_requirements: "Final inspection required.",
        depends_on: [10, 11],
      },
      {
        title: "Plumbing Finish",
        description: "Install all fixtures, faucets, toilets, and connect appliances.",
        trade_type: "Plumber",
        special_requirements: "Final inspection required.",
        depends_on: [10, 11, 12],
      },
      {
        title: "HVAC Finish",
        description: "Install registers, thermostats, and commission system. Balance airflow.",
        trade_type: "HVAC",
        special_requirements: "System startup and test required.",
        depends_on: [10],
      },
      {
        title: "Exterior Finish & Landscaping",
        description: "Siding, exterior paint or stain, driveway, walkways, grading, and landscaping.",
        trade_type: "Painter",
        special_requirements: "Final grade must slope away from foundation.",
        depends_on: [3],
      },
      {
        title: "Final Punch List & Inspection",
        description: "Walk-through, punch list items, final cleaning, and certificate of occupancy inspection.",
        trade_type: "General Contractor",
        special_requirements: "All permits must be closed. Compile warranty documents.",
        depends_on: [13, 14, 15, 16],
      },
    ],
  },
];
