import { ProjectTemplate } from "./types";

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    name: "Bathroom Remodel",
    project_type: "Bathroom Remodel",
    blocks: [
      {
        title: "Bathroom Demolition",
        description: "Remove existing fixtures, tile, vanity, and flooring.",
        trade_type: "Carpenter",
        special_requirements: "Cap all plumbing lines before demo.",
        depends_on: [],
      },
      {
        title: "Plumbing Rough-In",
        description: "Relocate or update supply and drain lines per new layout.",
        trade_type: "Plumber",
        special_requirements: "Permit required.",
        depends_on: [0],
      },
      {
        title: "Electrical Updates",
        description: "Update wiring for new lighting, fan, and GFCI outlets.",
        trade_type: "Electrician",
        special_requirements: "All outlets must be GFCI protected.",
        depends_on: [0],
      },
      {
        title: "Waterproofing & Tile",
        description: "Apply waterproofing membrane, install wall and floor tile.",
        trade_type: "Tile Installer",
        special_requirements: "Use Kerdi or equivalent waterproofing system.",
        depends_on: [1, 2],
      },
      {
        title: "Vanity & Fixture Installation",
        description: "Install vanity, toilet, faucets, shower fixtures, and accessories.",
        trade_type: "Plumber",
        special_requirements: "",
        depends_on: [3],
      },
      {
        title: "Painting & Trim",
        description: "Paint walls and ceiling. Install baseboards and trim.",
        trade_type: "Painter",
        special_requirements: "Use moisture-resistant paint.",
        depends_on: [3],
      },
    ],
  },
  {
    name: "Kitchen Remodel",
    project_type: "Kitchen Remodel",
    blocks: [
      {
        title: "Kitchen Demolition",
        description: "Remove existing cabinets, countertops, backsplash, and flooring.",
        trade_type: "Carpenter",
        special_requirements: "Protect adjacent rooms.",
        depends_on: [],
      },
      {
        title: "Electrical Rough-In",
        description: "Run new circuits for appliances and lighting.",
        trade_type: "Electrician",
        special_requirements: "Must comply with current NEC code.",
        depends_on: [0],
      },
      {
        title: "Plumbing Rough-In",
        description: "Update or relocate water supply and drain lines.",
        trade_type: "Plumber",
        special_requirements: "Include gas line if needed.",
        depends_on: [0],
      },
      {
        title: "Cabinet Installation",
        description: "Install wall and base cabinets per design plan.",
        trade_type: "Carpenter",
        special_requirements: "Level to within 1/16 inch.",
        depends_on: [1, 2],
      },
      {
        title: "Countertop Installation",
        description: "Template, fabricate, and install countertops.",
        trade_type: "Carpenter",
        special_requirements: "Template after cabinets are complete.",
        depends_on: [3],
      },
      {
        title: "Electrical Finish",
        description: "Install outlets, switches, and light fixtures.",
        trade_type: "Electrician",
        special_requirements: "",
        depends_on: [3],
      },
      {
        title: "Plumbing Fixtures",
        description: "Install sink, faucet, garbage disposal, dishwasher connection.",
        trade_type: "Plumber",
        special_requirements: "",
        depends_on: [4],
      },
      {
        title: "Tile Backsplash",
        description: "Install tile backsplash from countertop to underside of wall cabinets.",
        trade_type: "Tile Installer",
        special_requirements: "",
        depends_on: [4],
      },
      {
        title: "Painting",
        description: "Paint walls, ceiling, and touch up any trim.",
        trade_type: "Painter",
        special_requirements: "",
        depends_on: [5, 7],
      },
    ],
  },
  {
    name: "Deck Construction",
    project_type: "Deck Construction",
    blocks: [
      {
        title: "Site Preparation & Footings",
        description: "Excavate, set footings, and pour concrete piers.",
        trade_type: "Carpenter",
        special_requirements: "Permit and inspection required.",
        depends_on: [],
      },
      {
        title: "Framing",
        description: "Install ledger board, beams, joists, and blocking.",
        trade_type: "Carpenter",
        special_requirements: "Use pressure-treated lumber.",
        depends_on: [0],
      },
      {
        title: "Electrical for Outdoor Lighting",
        description: "Run circuits for deck lighting and outdoor outlets.",
        trade_type: "Electrician",
        special_requirements: "All outdoor-rated and GFCI protected.",
        depends_on: [1],
      },
      {
        title: "Decking & Railings",
        description: "Install deck boards, railings, and stairs.",
        trade_type: "Carpenter",
        special_requirements: "Railing must meet local code height requirements.",
        depends_on: [1],
      },
      {
        title: "Finishing & Staining",
        description: "Sand, stain, and seal all wood surfaces.",
        trade_type: "Painter",
        special_requirements: "Use exterior-grade stain/sealer.",
        depends_on: [2, 3],
      },
    ],
  },
];
